### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by DrakeLambert** [The-Grace-Bomb-Company/Grace-Bomb-App#1]
- Setup Google Play developer account
- Document local debug and publish steps for Android
- Automate build and beta deploy on push to `main`

**Comment by nolanrsherman** [comment]
I believe I can take this on. I have experience here. I have never published a flutter android app specifically, but have built plenty of them for local development and published other apps.

**Comment by nolanrsherman** [comment]
### Tasks

- [ ] Setup Google Play developer account
- [ ] Document Local Debug and Publish Steps for Android
- [ ] Automate Build and Beta Deploy on 'push' to `main`

**Comment by nolanrsherman** [comment]
@DrakeLambert do we have a google play account already? Any preference on the google account? I usually use something like googleadmin@mydomain.com, or if you want to keep it very specific to the app  and a standard gmail account: gracebomb-app-admin@gmail.com.

**Comment by DrakeLambert** [comment]
We used to have one under gracebombco@gmail.com, but google closed our dev account due to inactivity. Let's talk with Pat next week about a good alternative email that he can retain control of
